# backend/app/waf_service.py
"""
WAF Detection — определяет наличие Web Application Firewall
по HTTP-заголовкам, cookie, поведению сервера и IP.
"""
import logging
from typing import Dict, Optional
import requests

logger = logging.getLogger(__name__)

WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": {
            "server":          "cloudflare",
            "cf-ray":          None,
            "cf-cache-status": None,
        },
        "cookies": ["__cfduid", "cf_clearance", "__cf_bm"],
        "body_patterns": ["Attention Required! | Cloudflare", "cloudflare-nginx"],
        "icon": "🌐",
        "risk_impact": "low",
        "description": "Cloudflare WAF/CDN detected. DDoS protection, bot mitigation and WAF rules active.",
    },
    "AWS WAF": {
        "headers": {
            "x-amzn-requestid": None,
            "x-amz-cf-id":      None,
            "x-amz-id-2":       None,
        },
        "cookies": ["aws-waf-token"],
        "body_patterns": ["Request blocked", "AWS WAF"],
        "icon": "☁️",
        "risk_impact": "low",
        "description": "Amazon Web Services WAF detected. Managed rules protect against OWASP Top 10.",
    },
    "Akamai": {
        "headers": {
            "x-check-cacheable":    None,
            "x-akamai-transformed": None,
            "akamai-origin-hop":    None,
            "x-akamai-request-id":  None,
        },
        "cookies": ["ak_bmsc", "bm_sz"],
        "body_patterns": ["AkamaiGHost", "Reference #"],
        "icon": "🔒",
        "risk_impact": "low",
        "description": "Akamai Kona Site Defender detected. Enterprise-grade DDoS and WAF protection.",
    },
    "Imperva / Incapsula": {
        "headers": {
            "x-iinfo": None,
            "x-cdn":   "incapsula",
        },
        "cookies": ["incap_ses", "visid_incap"],
        "body_patterns": ["Powered by Incapsula", "incapsula incident"],
        "icon": "🛡️",
        "risk_impact": "low",
        "description": "Imperva Incapsula WAF detected. Advanced bot protection and DDoS mitigation.",
    },
    "Sucuri": {
        "headers": {
            "x-sucuri-id":    None,
            "x-sucuri-cache": None,
            "server":         "sucuri/cloudproxy",
        },
        "cookies": [],
        "body_patterns": ["Access Denied - Sucuri Website Firewall"],
        "icon": "🔐",
        "risk_impact": "low",
        "description": "Sucuri CloudProxy WAF detected. Website firewall with malware scanning.",
    },
    "F5 BIG-IP ASM": {
        "headers": {
            "server": "big-ip",
        },
        "cookies": ["ts"],
        "body_patterns": ["The requested URL was rejected", "F5 Networks"],
        "icon": "⚙️",
        "risk_impact": "low",
        "description": "F5 BIG-IP Application Security Manager detected.",
    },
    "Nginx ModSecurity": {
        "headers": {
            "server": "nginx",
        },
        "cookies": [],
        "body_patterns": ["ModSecurity", "NAXSI", "This error was generated by Mod_Security"],
        "icon": "🔧",
        "risk_impact": "medium",
        "description": "ModSecurity/NAXSI WAF on Nginx detected. Open-source WAF rules active.",
    },
}


def detect_waf(domain: str) -> Dict:
    result = {
        "detected":     False,
        "name":         None,
        "confidence":   None,
        "icon":         None,
        "description":  None,
        "risk_impact":  None,
        "signals":      [],
        "blocked_test": False,
    }

    headers_normal = {}
    cookies_normal = set()
    body_normal    = ""

    # Обычный запрос
    for scheme in ["https", "http"]:
        try:
            r = requests.get(
                f"{scheme}://{domain}",
                timeout=8,
                headers={"User-Agent": "Mozilla/5.0 (compatible; ThreatScope/1.0)"},
                allow_redirects=True,
            )
            headers_normal = {k.lower(): v.lower() for k, v in r.headers.items()}
            cookies_normal = {k.lower() for k in r.cookies.keys()}
            body_normal    = r.text[:3000].lower()
            break
        except Exception:
            continue

    if not headers_normal:
        return result

    # Тестовый payload
    try:
        r_atk = requests.get(
            f"https://{domain}/?q=<script>alert(1)</script>&id=1 OR 1=1--",
            timeout=8,
            headers={"User-Agent": "sqlmap/1.0"},
            allow_redirects=False,
        )
        if r_atk.status_code in (403, 406, 429, 503):
            result["blocked_test"] = True
    except Exception:
        pass

    # Matching
    best_score  = 0
    best_waf    = None
    best_signals = []

    for waf_name, sig in WAF_SIGNATURES.items():
        signals = []
        score   = 0

        for hdr, pattern in sig.get("headers", {}).items():
            if hdr in headers_normal:
                if pattern is None or pattern in headers_normal[hdr]:
                    signals.append(f"Header: {hdr}")
                    score += 3

        for cookie in sig.get("cookies", []):
            if cookie.lower() in cookies_normal:
                signals.append(f"Cookie: {cookie}")
                score += 3

        for pattern in sig.get("body_patterns", []):
            if pattern.lower() in body_normal:
                signals.append(f"Body: {pattern[:40]}")
                score += 4

        if score > best_score:
            best_score   = score
            best_waf     = waf_name
            best_signals = signals

    if best_waf and best_score > 0:
        confidence = "high" if best_score >= 6 else ("medium" if best_score >= 3 else "low")
        sig = WAF_SIGNATURES[best_waf]
        result.update({
            "detected":    True,
            "name":        best_waf,
            "confidence":  confidence,
            "icon":        sig["icon"],
            "description": sig["description"],
            "risk_impact": sig["risk_impact"],
            "signals":     best_signals,
        })
        logger.info(f"WAF: {best_waf} (confidence={confidence}, score={best_score})")
    elif result["blocked_test"]:
        result.update({
            "detected":    True,
            "name":        "Unknown WAF",
            "confidence":  "low",
            "icon":        "🛡️",
            "description": "An unidentified WAF blocked the test payload (HTTP 403/406). Fingerprint not matched.",
            "risk_impact": "low",
            "signals":     ["Blocked attack test request"],
        })
    else:
        logger.info(f"No WAF detected for {domain}")

    return result


def waf_to_finding(waf_result: Dict) -> Optional[Dict]:
    if not waf_result.get("detected"):
        return {
            "title": "No WAF / Firewall Detected",
            "severity": "Medium",
            "score": 6.0,
            "description": (
                "No Web Application Firewall was identified. "
                "The application is directly exposed without WAF protection, "
                "increasing risk from automated attacks and OWASP Top 10 exploits."
            ),
        }
    name = waf_result["name"]
    confidence = waf_result["confidence"]
    return {
        "title": f"WAF Detected: {name}",
        "severity": "Info",
        "score": 2.0,
        "description": (
            f"{waf_result['description']} "
            f"Detection confidence: {confidence}. "
            f"Signals: {', '.join(waf_result.get('signals', [])[:3])}."
        ),
    }
